[tool.poetry]
name = "mcculloch-pitts-neuron"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
